version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:22-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
